#[cfg(test)]
mod tests {
    use crate::into_test::*;

    /// Test the implementation of [std::convert::Into] generated by inter-struct.
    #[test]
    fn merge_identical() {
        // The base struct that's going to be merged into.
        let from = FromStruct::new();

        let into = IntoStruct::from(from);
        assert_eq!(into.normal, "from");
        assert_eq!(into.optional, Some("from".to_string()));
    }
}
